apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleappprod
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: v1.0.0
  template:
    metadata:
      annotations:
        owner: team-iac
      labels:
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v4
          name: main
          resources:
            limits:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 100Mi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 100Mi
---
apiVersion: v1
kind: Namespace
metadata:
  name: sampleapp
